In [1]:
from enhancedDecoder import ModernBertLayerForDecoder, ModernBERTCrossAttention

/mnt/raid6/yjoonjang/miniconda3/envs/kurev2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from transformers import ModernBertConfig
config = ModernBertConfig()

In [3]:
decoder = ModernBertLayerForDecoder(config)
decoder

ModernBertLayerForDecoder(
  (attn): ModernBERTCrossAttention(
    (Wq): Linear(in_features=768, out_features=768, bias=False)
    (Wkv): Linear(in_features=768, out_features=1536, bias=False)
    (Wo): Linear(in_features=768, out_features=768, bias=False)
    (rotary_emb): ModernBertRotaryEmbedding()
  )
  (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (mlp): ModernBertMLP(
    (Wi): Linear(in_features=768, out_features=2304, bias=False)
    (act): GELUActivation()
    (drop): Dropout(p=0.0, inplace=False)
    (Wo): Linear(in_features=1152, out_features=768, bias=False)
  )
  (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)

In [6]:
decoder.bfloat16()

ModernBertLayerForDecoder(
  (attn): ModernBERTCrossAttention(
    (Wq): Linear(in_features=768, out_features=768, bias=False)
    (Wkv): Linear(in_features=768, out_features=1536, bias=False)
    (Wo): Linear(in_features=768, out_features=768, bias=False)
    (rotary_emb): ModernBertRotaryEmbedding()
  )
  (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  (mlp): ModernBertMLP(
    (Wi): Linear(in_features=768, out_features=2304, bias=False)
    (act): GELUActivation()
    (drop): Dropout(p=0.0, inplace=False)
    (Wo): Linear(in_features=1152, out_features=768, bias=False)
  )
  (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
)

In [8]:
import torch

encoder_attention_mask = torch.randint(0, 2, (1, 10))
encoder_attention_mask


tensor([[0, 1, 1, 1, 0, 1, 0, 0, 1, 1]])

In [10]:
seqlens_in_batch = encoder_attention_mask.sum(dim=-1, dtype=torch.int32)
seqlens_in_batch

tensor([6], dtype=torch.int32)

In [11]:
cu_seqlens = torch.nn.functional.pad(torch.cumsum(seqlens_in_batch, dim=0, dtype=torch.int32), (1, 0))
cu_seqlens

tensor([0, 6], dtype=torch.int32)

In [12]:
cls_indices = cu_seqlens[:-1]
cls_indices

tensor([0], dtype=torch.int32)